config/routes.rb
  post 'articles/status' => 'articles#update_tracked_status'

  resources :courses_users, only: [:index]
  resources :alerts, only: [:create] do
    member do
      get 'resolve'
      put 'resolve'
    end
    collection do
      post 'notify_instructors'
    end
  end

  put 'greeting' => 'greeting#greet_course_students'

  # Article Finder
  get 'article_finder' => 'article_finder#index'

  # Reports and analytics
  get 'analytics(/*any)' => 'analytics#index'
  post 'analytics(/*any)' => 'analytics#results'
  get 'usage' => 'analytics#usage'
  get 'ungreeted' => 'analytics#ungreeted'
  get 'course_csv' => 'analytics#course_csv'
  get 'course_edits_csv' => 'analytics#course_edits_csv'
  get 'course_uploads_csv' => 'analytics#course_uploads_csv'
  get 'course_students_csv' => 'analytics#course_students_csv'
  get 'course_articles_csv' => 'analytics#course_articles_csv'
  get 'course_revisions_csv' => 'analytics#course_revisions_csv'
  get 'course_wikidata_csv' => 'analytics#course_wikidata_csv'
  get 'all_courses_csv' => 'analytics#all_courses_csv'
  get 'all_courses' => 'analytics#all_courses'
  get 'all_campaigns' => 'analytics#all_campaigns'

  # Campaigns
  resources :campaigns, param: :slug, except: :show do
    member do
      get 'overview'
      get 'programs'
      get 'articles'
      get 'users'
      get 'assignments'
      get 'students'
      get 'instructors'
      get 'courses'
      get 'ores_plot'
      get 'articles_csv'
      get 'revisions_csv'
      get 'alerts'
      get 'wikidata'
      put 'add_organizer'
      put 'remove_organizer'
      put 'remove_course'
      get 'active_courses'
    end
  end

  get 'campaigns/statistics.json' => 'campaigns#statistics'
  get 'campaigns/:slug.json',
      controller: :campaigns,
      action: :show
  get 'campaigns/:slug', to: redirect('campaigns/%{slug}/programs')
  get 'campaigns/:slug/programs/:courses_query',
      controller: :campaigns,
      action: :programs,
      to: 'campaigns/%{slug}/programs?courses_query=%{courses_query}'
  get 'campaigns/:slug/ores_data.json' =>  'ores_plot#campaign_plot'
  get 'current_term(/:subpage)' => 'campaigns#current_term'

  # Courses by tag
  resources :tagged_courses, param: :tag do
    member do
      get 'programs'
      get 'articles'
      get 'alerts'
    end
  end

  # Recent Activity
  get 'recent-activity/plagiarism/report' => 'recent_activity#plagiarism_report'
  get 'recent-activity(/*any)' => 'recent_activity#index', as: :recent_activity

  # Revision analytics JSON API for React
  get 'revision_analytics/dyk_eligible',
      controller: 'revision_analytics',
      action: 'dyk_eligible'
  get 'revision_analytics/suspected_plagiarism',
      controller: 'revision_analytics',
      action: 'suspected_plagiarism'
  get 'revision_analytics/recent_edits',
      controller: 'revision_analytics',
      action: 'recent_edits'
  get 'revision_analytics/recent_uploads',
      controller: 'revision_analytics',
      action: 'recent_uploads'


  # Revision Feedback
  get '/revision_feedback' => 'revision_feedback#index'

  # Wizard
  get 'wizards' => 'wizard#wizard_index'
  get 'wizards/:wizard_id' => 'wizard#wizard'
  post 'courses/:course_id/wizard/:wizard_id' => 'wizard#submit_wizard',
       constraints: { course_id: /.*/ }

  # Training
  get 'training' => 'training#index'
  get 'training/:library_id' => 'training#show', as: :training_library
  get 'training/:library_id/:module_id' => 'training#training_module', as: :training_module
  get 'training_modules_users' => 'training_modules_users#index'
  post 'training_modules_users' => 'training_modules_users#create_or_update'
  post 'training_modules_users/exercise' => 'training_modules_users#mark_exercise_complete'
  get 'reload_trainings' => 'training#reload'

  get 'training_status' => 'training_status#show'
  get 'user_training_status' => 'training_status#user'

  # for React
  get 'training/:library_id/:module_id(/*any)' => 'training#slide_view'

  # API for slides for a module
  get 'training_modules' => 'training_modules#index'
  get 'training_module' => 'training_modules#show'

  # To find training modules by id
  get 'find_training_module/:module_id' => 'training_modules#find'

  # To find individual slides by id
  get 'find_training_slide/:slide_id' => 'training#find_slide'

  # Misc
  # get 'courses' => 'courses#index'
  get 'explore' => 'explore#index'
  get 'explore/search' => 'explore#search'
  get 'unsubmitted_courses' => 'unsubmitted_courses#index'
  get 'active_courses' => 'active_courses#index'
  get '/courses_by_wiki/:language.:project(.org)' => 'courses_by_wiki#show'

  # frequenty asked questions
  resources :faq
  get '/faq_topics' => 'faq_topics#index'
  get '/faq_topics/new' => 'faq_topics#new'
  post '/faq_topics' => 'faq_topics#create'
  get '/faq_topics/:slug/edit' => 'faq_topics#edit'
  post '/faq_topics/:slug' => 'faq_topics#update'
  delete '/faq_topics/:slug' => 'faq_topics#delete'

  # Authenticated users root to the courses dashboard
  authenticated :user do
    root to: "dashboard#index", as: :courses_dashboard
  end

  get 'dashboard' => 'dashboard#index'
  get 'my_account' => 'dashboard#my_account'

  # Unauthenticated users root to the home page
  root to: 'home#index'

  # Surveys
  mount Rapidfire::Engine => "/surveys/rapidfire", :as => 'rapidfire'
  get '/surveys/results' => 'surveys#results_index', as: 'results'
  resources :survey_assignments, path: 'surveys/assignments'
  post '/survey_assignments/:id/send_test_email' => 'survey_assignments#send_test_email', as: 'send_test_email'
  put '/surveys/question_position' => 'questions#update_position'
  get '/survey/results/:id' => 'surveys#results', as: 'survey_results'
  get '/survey/question/results/:id' => 'questions#results', as: 'question_results'
  get '/surveys/question_group_question/:id' => 'questions#question'
  get '/surveys/:id/question_group' => 'surveys#edit_question_groups', :as => "edit_question_groups"
  post '/surveys/question_group/clone/:id' => 'surveys#clone_question_group'
  post '/surveys/question/clone/:id' => 'surveys#clone_question'
  post '/surveys/update_question_group_position' => 'surveys#update_question_group_position'
  resources :surveys
  get '/surveys/:id/optout' => 'surveys#optout', as: 'optout'
  get '/surveys/select_course/:id' => 'surveys#course_select'
  put '/survey_notification' => 'survey_notifications#update'
  post '/survey_notification/create' => 'survey_assignments#create_notifications', as: 'create_notifications'
  post '/survey_notification/send' => 'survey_assignments#send_notifications', as: 'send_notifications'
  get '/survey/responses' => 'survey_responses#index'
  delete '/survey/responses/:id/delete' => 'survey_responses#delete'

  # Onboarding
  get 'onboarding(/*any)' => 'onboarding#index', as: :onboarding
  put 'onboarding/onboard' => 'onboarding#onboard', as: :onboard
  put 'onboarding/supplementary' => 'onboarding#supplementary', as: :supplementary

  # Update Locale Preference
  post '/update_locale/:locale' => 'users/locale#update_locale', as: :update_locale
  get '/update_locale/:locale' => 'users/locale#update_locale'

  # Route aliases for React frontend
  get '/course_creator(/*any)' => 'dashboard#index', as: :course_creator

  get '/feedback' => 'feedback_form_responses#new', as: :feedback
  get '/feedback_form_responses' => 'feedback_form_responses#index'
  get '/feedback_form_responses/:id' => 'feedback_form_responses#show', as: :feedback_form_response
  post '/feedback_form_responses' => 'feedback_form_responses#create'
  get '/feedback/confirmation' => 'feedback_form_responses#confirmation'

  # Salesforce
  if Features.wiki_ed?
    put '/salesforce/link/:course_id' => 'salesforce#link'
    put '/salesforce/update/:course_id' => 'salesforce#update'
    get '/salesforce/create_media' => 'salesforce#create_media'
  end

  # Wikimedia Event Center
  post '/wikimedia_event_center/confirm_event_sync' => 'wikimedia_event_center#confirm_event_sync'
  post '/wikimedia_event_center/update_event_participants' => 'wikimedia_event_center#update_event_participants'
  post '/wikimedia_event_center/unsync_event' => 'wikimedia_event_center#unsync_event'

  # Experiments
  namespace :experiments do
    get 'fall2017_cmu_experiment/:course_id/:email_code/opt_in' => 'fall2017_cmu_experiment#opt_in'
    get 'fall2017_cmu_experiment/:course_id/:email_code/opt_out' => 'fall2017_cmu_experiment#opt_out'
    get 'fall2017_cmu_experiment/course_list' => 'fall2017_cmu_experiment#course_list'
    get 'spring2018_cmu_experiment/:course_id/:email_code/opt_in' => 'spring2018_cmu_experiment#opt_in'
    get 'spring2018_cmu_experiment/:course_id/:email_code/opt_out' => 'spring2018_cmu_experiment#opt_out'
    get 'spring2018_cmu_experiment/course_list' => 'spring2018_cmu_experiment#course_list'
  end

  resources :admin
  resources :alerts_list

  namespace :mass_email do
    get 'term_recap' => 'term_recap#index'
    post 'term_recap/send' => 'term_recap#send_recap_emails'
  end

  get '/redirect/sandbox/:sandbox' => 'redirects#sandbox'

  resources :settings, only: [:index]

  authenticate :user, lambda { |u| u.admin? } do
    post '/tickets/reply' => 'tickets#reply', format: false
    post '/tickets/notify_owner' => 'tickets#notify_owner', format: false
    get '/tickets/search' => 'tickets#search', format: false
    get '/tickets/*dashboard' => 'tickets#dashboard', format: false
    mount TicketDispenser::Engine, at: "/td"
  end

  require 'sidekiq_unique_jobs/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/private_information' => 'about_this_site#private_information'
  get '/styleguide' => 'styleguide#index'

  # Errors
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/599', to: 'errors#login_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

app/models/surveys/question_group_conditional.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: question_group_conditionals
#
#  id                          :integer          not null, primary key
#  rapidfire_question_group_id :integer
#  campaign_id                 :integer
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#

class QuestionGroupConditional < ApplicationRecord
  belongs_to :rapidfire_question_group, class_name: 'Rapidfire::QuestionGroup'
  belongs_to :campaign
end

app/helpers/surveys_helper.rb
# frozen_string_literal: true

# Rubocop now wants us to remove instance methods from helpers. This is a good idea
# but will require a bit of refactoring. Find other instances of this disabling
# and fix all at once.
# rubocop:disable Rails/HelperInstanceVariable

module SurveysHelper
  include CourseHelper

  def survey_course_title
    if @course.nil? || !Features.wiki_ed?
      'Survey'
    else
      "Survey for #{@course.title} (#{@course.term})"
    end
  end

  def render_matrix_answer_labels(answer)
    render partial: 'rapidfire/answers/matrix_answer_labels',
           locals: { answer:, course: @course }
  end

  def survey_preview_url(survey)
    "#{survey_url(survey)}?preview"
  end

  def question_answer_field_name(form, multiple)
    name = "answer_group[#{form.object.question_id}][answer_text]"
    if multiple
      name + '[]'
    else
      name
    end
  end

  def survey_select(f, answer, course)
    multiple = answer.question.multiple
    field_name = question_answer_field_name(f, multiple)
    options = answer_options(answer, course)
              .collect { |o| o.is_a?(Array) ? [o[1].tr('_', ' ').to_s, o[0]] : o }
    return content_tag :div, 'remove me', data: { remove_me: true } if options.empty?
    select_tag(field_name, options_for_select(options),
               include_blank: multiple ? 'Select all that apply' : 'Select an option',
               required: required_question?(answer),
               multiple:)
  end

  def answer_options(answer, course)
    question = answer.question
    if !question.options.empty?
      question.options.collect { |q| [strip_tags(q), q, q] }
    elsif !course.nil?
      course_answer_options(question.course_data_type, course)
    end
  end

  def course_answer_options(type, course)
    case type
    when 'Students'
      course_student_choices(course)
    when 'Articles'
      course_article_choices(course)
    when 'WikiEdu Staff'
      course_wikiedu_staff_choices(course)
    end
  end

  def can_administer?
    current_user&.admin?
  end

  def required_question?(answer)
    answer.question.validation_rules[:presence].to_i == 1
  end

  def question_is_grouped?(answer)
    return false if answer.nil? || answer.question.nil?
    answer.question.validation_rules[:grouped].to_i == 1
  end

  def grouped_question(answer)
    answer.question.validation_rules[:grouped_question]
  end

  # rubocop:disable Metrics/MethodLength
  def question_group_locals(surveys_question_group, index, total, is_results_view:)
    @question_group = surveys_question_group.rapidfire_question_group
    @answer_group_builder = Rapidfire::AnswerGroupBuilder.new(params: {},
                                                              user: current_user,
                                                              question_group: @question_group)
    @questions = surveys_question_group
                 .rapidfire_question_group
                 .questions
                 .includes(answers: { user: :survey_notifications })

    @id_to_question = {}
    @questions.each do |question|
      @id_to_question[question.id] = question
    end

    @question_answers_count = Rapidfire::Answer
                              .where(question_id: @questions.pluck(:id))
                              .group(:question_id).count

    @answer_group_builder.answers.each do |answer|
      question = @id_to_question[answer.question_id]
      answer.question = question
    end

    return { question_group: @question_group,
      answer_group_builder: @answer_group_builder,
      question_group_index: index,
      surveys_question_group:,
      total:,
      results: is_results_view }
  end
  # rubocop:enable Metrics/MethodLength

  def question_conditional_string(question)
    return '' if question.nil?
    return '' unless valid_conditional_question?(question.conditionals)
    return question.conditionals
  end

  def course_data?(question_form)
    question_form.course_data_type.present?
  end

  def question_form_has_follow_up_question(question_form)
    question_form.follow_up_question_text.present?
  end

  def conditional_attribute(answer)
    return unless answer.question.conditionals?
    string = strip_tags(answer.question.conditionals).tr(' ', '_').tr("'", "\\'")
    string
  end

  def numeric_min(answer)
    rule = answer.question.rules[:greater_than_or_equal_to]
    rule.empty? ? '0' : rule
  end

  def numeric_max(answer)
    rule = answer.question.rules[:less_than_or_equal_to]
    rule.empty? ? '999999999' : rule
  end

  def valid_conditional_question?(conditional_string)
    return false if conditional_string.nil?
    question_id = conditional_string.split('|').first.to_i
    Rapidfire::Question.exists?(question_id)
  end

  private

  def survey_notification_id(notification)
    return nil if notification == false || notification.nil?
    return notification.id
  end

  def survey_class_for_path(req, path)
    current_path_segments = req.path.split('/').reject(&:blank?)
    active_path = path.split('/').reject(&:blank?).last
    current_path_segments.last == active_path ? 'active' : nil
  end

  ######################
  # Setting the course #
  ######################

  # If at all possible, find the course to associate with this survey.
  # Setting a course is necessary for conditional features of surveys — question
  # groups that only apply to certain campaigns, or for courses with certain tags
  # — to work.
  # First go based on slug. Next, go based on notification.
  # For preview mode, fall back to the course_select dropdown.
  # For a real survey, fall back to the user's latest course.
  def set_course
    @course = find_course_by_slug(params[:course_slug]) if course_slug?
    @course ||= @notification.course if @notification.instance_of?(SurveyNotification)
    return if @course
    if preview_mode?
      set_course_via_select
    else
      fall_back_to_last_course_for_user
    end
  end

  def set_course_via_select
    @courses = Course.all
    render 'course_select'
  end

  def fall_back_to_last_course_for_user
    @course = current_user.courses.last
  end

  def preview_mode?
    params.key?(:preview)
  end

  ######################################
  # Methods called only from this file #
  ######################################

  def course_student_choices(course)
    students = course.courses_users.where(role: CoursesUsers::Roles::STUDENT_ROLE)
    students.collect { |cu| [cu.user.id, cu.user.username, contribution_link(cu).to_s] }
  end

  def course_article_choices(course)
    course.articles.collect do |a|
      [a.url, a.title, "<a href='#{a.url}' target='_blank'>#{a.title}</a>"]
    end
  end

  def course_wikiedu_staff_choices(course)
    staff = course.courses_users.where(role: CoursesUsers::Roles::WIKI_ED_STAFF_ROLE)
    staff.collect { |cu| [cu.user.id, cu.user.username, contribution_link(cu).to_s] }
  end

  def course_slug?
    params.key?(:course_slug)
  end
end

# rubocop:enable Rails/HelperInstanceVariable

app/views/surveys/_form.html.haml
= simple_form_for(@survey) do |f|
  = f.error_notification
  = render partial: 'surveys/admin_header_edit', locals: { f: f }
  .container.survey__admin
    .form__block.form__block--equal-height
      .block.form__settings
        .form__settings__tabs
          .tab
            %h3 Settings
        .form-inputs.light-text.survey__title-input
          = f.input :name

        .form-inputs.light-text.survey__title-input
          = f.input :open, label: "Survey Open (Anyone may take it)"
          = f.input :closed, label: "Close Survey"
        .form__actions.danger
          = link_to 'Delete this survey', @survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

      .form__question-group-list
        .light-text
          %h3 Survey Question Groups
          %div.py= link_to "Edit Question Groups", edit_question_groups_path(@survey.id)

        - if @surveys_question_groups.length > 1
          .survey__admin-tools
            .contextual Drag to reorder questions. (Changes will be saved automatically.)

        - if @surveys_question_groups.length
          %table.table.list--survey{'data-sortable-question-groups' => @survey.id}
            %tbody
              - @surveys_question_groups.each do |group|
                - question_group = group.rapidfire_question_group
                %tr.question-group-row.row.course-list__row.row--survey-question{'data-item-id' => question_group.id}
                  %td
                    .course-list__row__title
                      %strong= question_group.name
                  %td
                    %div= link_to "Edit", rapidfire.edit_question_group_path(question_group)


        %div.light-text
          = f.label :intro, "Survey Introduction"
          = f.hidden_field :intro , id: 'intro', value: @survey.intro
          = f.text_area :intro

        %div.light-text
          = f.label :thanks, "Survey Thank You"
          = f.hidden_field :thanks , id: 'thanks', value: @survey.thanks
          = f.text_area :thanks

        %div.light-text
          = f.label :optout, "Opt out message"
          = f.hidden_field :optout , id: 'optout', value: @survey.optout
          = f.text_area :optout

        .form__actions
          = f.button :submit, :class => 'button dark'
          = link_to "Preview Survey", survey_preview_url(@survey), :class => 'button'

app/views/surveys/_loading.html.haml
.spinner
  .bounce1
  .bounce2
  .bounce3

app/views/surveys/_navigation.html.haml
- if can_administer?
  .survey__admin__nav
    %nav.container
      %div.nav__item= link_to 'Question Groups', rapidfire.question_groups_path, class: survey_class_for_path(request, rapidfire.question_groups_path)
      %div.nav__item= link_to 'Surveys', main_app.surveys_path, class: survey_class_for_path(request, main_app.surveys_path)
      %div.nav__item= link_to 'Assignment', main_app.survey_assignments_path, class: survey_class_for_path(request, main_app.survey_assignments_path)
      %div.nav__item= link_to 'Results', main_app.results_path, class: survey_class_for_path(request, main_app.results_path)
      %div.nav__item= link_to 'Recent Responses', main_app.survey_responses_path, class: survey_class_for_path(request, main_app.survey_responses_path)

app/views/surveys/_question_group.html.haml
- content_for :after_title, ' – Question Groups'

= form_for(Rapidfire::AnswerGroup.new,
    :url => rapidfire.question_group_answer_groups_path(question_group),
    :html => {:'data-survey-form' => true, :'data-question-group' => question_group_index, :tabindex => -1 }) do |f|

  - group_index_data = results ? '' : question_group_index
  %div{:'data-question-group-blocks' => group_index_data}
    - @answer_group_builder.answers.each_with_index do |answer, index|
      - question_presenter = RapidfireQuestionPresenter.new(answer, index: index,
          answer_group_builder: @answer_group_builder, is_results_view: results)
      - next if question_presenter.results_view? && question_presenter.text_only?
      - is_start_of_group = question_presenter.start_of_group?
      - is_end_of_group = question_presenter.end_of_group?

      - if is_start_of_group
        <div class="block__container" data-block-index="#{index}" data-survey-index=""><div class="block not-seen disabled survey__question--matrix #{question_presenter.question_type}">

      = f.fields_for("#{answer.question.id}", answer) do |answer_form|
        = render partial: "rapidfire/answers/matrix_question_text", locals: {f: f, answer: answer, name: question_group.name}

        - if !question_presenter.grouped_question?
          <div class="block__container"><div data-survey-block="#{index + 1}" id="question_#{answer.question.id}" class="block disabled not-seen question-type--#{question_presenter.question_type} #{answer.errors.any? ? block--errors : ''} #{question_presenter.required_class}"> 

        - if question_presenter.start_of_radio_matrix?
          %div{:class => "survey__question-row first matrix-row", :'data-block-index' => "#{index}"}
            = render_matrix_answer_labels(answer)

        %div{:'data-question-group' => "#{question_group_index}",
         :'data-conditional-question' => conditional_attribute(answer),
         :id => question_presenter.grouped_question? ? "question_#{answer.question.id}" : "",
         :class => "survey__question-row #{question_presenter.grouped_question? ? 'matrix-row' : ''} " + |
                   "#{question_presenter.required_class} " +               |
                   "#{index.even? ? '' : 'odd'} #{is_end_of_group ? 'last' : ''}" }

          - if results
            = render partial: "rapidfire/answers/question_text", locals: {f: answer_form, answer: answer}
            = render partial: "question_results", locals: { question: @id_to_question[answer.question.id], survey_user_cache: @survey_user_cache }
          - else
            = render_answer_form_helper(answer, answer_form)

        / After single question or final grouped question
        - if is_end_of_group && !results
          - if question_presenter.follow_up_question?
            = render partial: "rapidfire/answers/follow_up_question", locals: {f: answer_form, answer: answer }

          / Prev/Next/Submit
          %div{:class => "survey__block-nav"}
            %button{:tabindex => "-1", :class => "button survey__prev border", :'data-prev-survey-block' => ""}= "Previous"
            %div{:class => "survey__block-nav__next-container"}
              %div{:'data-errors' => ""}
              %button{:tabindex => "-1", :class => "button survey__next dark", :'data-next-survey-block' => ""}
                %span{:class => "survey__next-text"}= "Next"
                %span{:class => "icon icon-rt_arrow"}

      - if is_end_of_group
        </div></div>

app/views/surveys/_question_results.html.haml
%div{data: { question_results: question_results_data(question, survey_user_cache) }}
.results__question-footer
  %strong= respondents(question, @question_answers_count)
  = link_to "Download Results CSV", question_results_path(question, format: 'csv')

app/views/surveys/_results_admin_header.html.haml
- content_for :after_title, ' – Survey Results'

.section-header.surveys__admin-header.surveys__admin-header--survey_results
  .container
    %div
      %h1 Survey Results
    .surveys__admin-header__action
      -#

app/views/surveys/_survey.html.haml
%li.survey__admin-row.survey__admin-row--survey
  .survey__admin-row__title
    %strong.name= survey.name
  .survey__admin-row__col
    .contextual Status
    %strong.survey-color.status= survey_status(survey)
  .survey__admin-row__col
    .contextual Groups | Questions
    %strong= survey_question_stats(survey)
  .survey__admin-row__col
    .contextual Last Author
    %span.author= survey_author(survey)
  -# .survey__admin-row__col
  -#   .contextual Created
  -#   %span= survey.created_at.strftime("%B %d, %Y")
  .survey__admin-row__col
    .contextual Updated
    %span= survey.updated_at.strftime("%B %d, %Y")
  .survey__admin-row__col.survey__admin-row__col--actions
    = link_to 'Edit', edit_survey_path(survey)
    - if survey.rapidfire_question_groups.length > 0
      = link_to 'Preview', "#{survey_url(survey)}?preview"
    = link_to 'Results', survey_results_path(survey)
    -# .course-list__col
    -#   = link_to 'Delete', survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/surveys/course_select.html.haml
.block.block--text.disabled.not-seen{"data-survey-block" => "0", "data-intro" => true}
  %h1.survey__title= @survey.name
  %p Select a Course for Survey
  = form_tag survey_path(@survey), method: "get" do
    - if params.has_key?(:preview)
      = check_box_tag "preview", true, true, class: 'hidden'
    = select_tag "course_slug", options_from_collection_for_select(@courses, 'slug', 'title'), required: true, include_blank: true, survey_course_select: true, placeholder: "Select your course"
    .survey__block-nav
      = submit_tag "Start Survey", class: 'button dark pull-right'

app/views/surveys/edit_question_groups.html.haml
= render 'admin_header'
.block.block--clear

  %h3 Editing Question Groups for "#{@survey.name}" Survey

  = simple_form_for(@survey) do |f|
    = f.error_notification

    .form-input
      = f.association :rapidfire_question_groups,   as: :check_boxes

    .form-actions
      = f.button :submit, "Update Question Groups", :class => 'button dark'

app/views/surveys/index.html.haml
- content_for :before_title, 'Surveys — '

= render 'admin_header'
.container.survey__edit
  - if @surveys.length > 0
    %ul.list= render partial: "survey", collection: @surveys.reverse
  - else
    %p.light-text
      No Surveys. #{link_to "Create One", new_survey_path}

app/views/surveys/login.html.haml
.block.text-center.survey__login
  %h1= @survey.name
  %p.lead= t('survey.login_message')
  = link_to user_mediawiki_omniauth_authorize_path, class: 'button dark', method: :post do
    %i.icon.icon-wiki-logo-purple
    %span= t('application.log_in')
    %span= t('application.sign_up_log_in_extended')

app/views/surveys/new.html.haml
= render 'admin_header'
.container.survey__admin
  .block.block--clear
    = simple_form_for(@survey) do |f|
      = f.error_notification

      .form-inputs.survey__title-input
        = f.input :name

        .form__row
          = f.button :submit, :class => 'button dark'

app/views/surveys/optout.html.haml
.container
  %header
    %h1
      You've opted out of:
    %h3= @survey.name

  %section
    %div
      %p= @survey&.optout&.html_safe

app/views/surveys/show.html.haml
- if params.key?("preview")
  .survey-previewing Preview Mode

// Used for logging survey data via Sentry
:javascript
  SurveyDetails = {
    id: "#{@survey.id}"
  }

%p#notice= notice

%div{data: {survey_form_container: true, notification: survey_notification_id(@notification)}, class: 'loading'}
  - if @survey.intro?
    .block__container
      .block.block--text.disabled.not-seen{"data-survey-block" => "0", "data-intro" => true}
        %h1.survey__title= @survey.name
        - if @survey.intro?
          - if @survey.confidential_results
            = @survey.intro.html_safe
            .survey__block-nav
              %a.button.survey__prev.border{"href" => "/surveys/#{@survey.id}/optout"}
                %span No, I do not agree
              %button.button.survey__next.dark{"data-next-survey-block" => "", "start-survey" => "", "data-no-validate" => true}
                %span Yes, I agree
                %span.icon.icon-rt_arrow
          - else
            = @survey.intro.html_safe
            .survey__block-nav
              %div
              %button.button.survey__next.dark{"data-next-survey-block" => "", "start-survey" => "", "data-no-validate" => true}
                %span Start
                %span.icon.icon-rt_arrow


  - @surveys_question_groups.each_with_index do |group, index|
    = render partial: "question_group", locals: question_group_locals(group, index, @surveys_question_groups.length, is_results_view: false)

  .block__container
    .block.block--text.block--clear.block--thank-you.disabled.not-seen{data: {thank_you: true}}
      .block--thank-you__container
        %h2.big-title Thank You!
        - if @survey.thanks?
          = @survey.thanks.html_safe